server:
  port: 8888

spring:
  application:
    name: config-service
  
  # Config server settings
  cloud:
    config:
      server:
        git:
          uri: classpath:/config-repo
          default-label: main
        native:
          search-locations: classpath:/config-repo
  
  profiles:
    active: native

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30

# Security
  security:
    user:
      name: config
      password: config123

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,configprops
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
# Docker profile
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/ 