spring:
  profiles:
    active: local
  
  datasource:
    url: jdbc:postgresql://localhost:5432/bookvault
    username: bookvault
    password: bookvault123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # Disable config service for local development
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

server:
  port: 8083

# External service URLs for local development
auth:
  service:
    url: http://localhost:8082

# Enable all actuator endpoints for local development
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# CORS configuration for local development
cors:
  allowed-origins: http://localhost:8080,http://localhost:3000,http://127.0.0.1:8080,http://127.0.0.1:3000

# Logging configuration for local development
logging:
  level:
    com.bookvault: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx" 