server:
  port: 8082

spring:
  application:
    name: auth-service
  
  # Disable config server import check for local development
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  
  # OPTIMIZED Database configuration with connection pooling
  datasource:
    url: jdbc:postgresql://localhost:5432/bookvault
    username: bookvault
    password: bookvault123
    driver-class-name: org.postgresql.Driver
    # OPTIMIZATION: Connection pooling for better performance
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
      pool-name: AuthServiceHikariCP
  
  # JPA configuration - Fixed autoCommit issue
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        # OPTIMIZATION: Enable batch processing
        jdbc:
          batch_size: 20
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  # Redis configuration - only configured for Docker profile
  # redis configuration is profile-specific - see docker profile below

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# JWT configuration
jwt:
  secret: bookvault-secret-key-that-should-be-very-long-and-secure-in-production
  expiration: 86400000 # 24 hours in milliseconds

# OPTIMIZED Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# OPTIMIZED Logging - Reduce noise, improve performance
logging:
  level:
    com.bookvault.auth: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    com.zaxxer.hikari: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
# Docker profile
spring:
  config:
    activate:
      on-profile: docker
  
  # Disable config service for Docker (same as local)
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  
  datasource:
    url: jdbc:postgresql://postgres:5432/bookvault
  
  # Redis configuration for Docker - hardcoded for container networking
  redis:
    host: redis
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    password: # no password for Docker

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

---
# Railway profile
spring:
  config:
    activate:
      on-profile: railway
  
  # Disable config service for Railway
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:${DATABASE_URL}}
    username: ${SPRING_DATASOURCE_USERNAME:${DATABASE_USERNAME}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DATABASE_PASSWORD}}
    driver-class-name: org.postgresql.Driver
  
  # Redis configuration for Railway - using environment variables
  redis:
    host: ${SPRING_REDIS_HOST:${REDIS_HOST:localhost}}
    port: ${SPRING_REDIS_PORT:${REDIS_PORT:6379}}
    username: ${SPRING_REDIS_USERNAME:${REDIS_USERNAME:}}
    password: ${SPRING_REDIS_PASSWORD:${REDIS_PASSWORD:}}
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  
  main:
    lazy-initialization: true

server:
  port: ${SERVER_PORT:8080}

# CORS configuration for Railway
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://*.railway.app,https://*.netlify.app,https://*.vercel.app}

# Logging configuration for Railway
logging:
  level:
    com.bookvault: INFO
    org.springframework: WARN
    org.hibernate: WARN
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Management endpoints for Railway
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true/ 