server:
  port: 8082

spring:
  application:
    name: auth-service
  
  # Disable config server import check for local development
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  
  # OPTIMIZED Database configuration with connection pooling
  datasource:
    url: jdbc:postgresql://localhost:5432/bookvault
    username: bookvault
    password: bookvault123
    driver-class-name: org.postgresql.Driver
    # OPTIMIZATION: Connection pooling for better performance
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
      pool-name: AuthServiceHikariCP
  
  # JPA configuration - Fixed autoCommit issue
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        # OPTIMIZATION: Enable batch processing
        jdbc:
          batch_size: 25
          order_inserts: true
          order_updates: true
        # OPTIMIZATION: Database dialect optimizations
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
  
  data:
    redis:
      enabled: false # Disable Redis by default for local development
      
# JWT configuration
jwt:
  secret: bookvault-secret-key-that-should-be-very-long-and-secure-in-production-environment-with-at-least-32-characters
  expiration: 86400000 # 24 hours in milliseconds

# Eureka client configuration - DISABLED for local development
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
    enabled: false
  instance:
    prefer-ip-address: true

# OPTIMIZED Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# OPTIMIZED Logging - Reduce noise, improve performance
logging:
  level:
    com.bookvault.auth: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.springframework.web: WARN
    com.zaxxer.hikari: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
# Docker profile
spring:
  config:
    activate:
      on-profile: docker
  
  # Disable config service for Docker (same as local)
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  
  datasource:
    url: jdbc:postgresql://postgres:5432/bookvault

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

---
# Railway profile
spring:
  config:
    activate:
      on-profile: railway

  data:
    redis:
      enabled: true
      host: ${REDIS_HOST:redis.railway.internal}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:nvJhLcRzJNaXJNUlLFEUCrcFZJMJbQiM}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10  # Reduced for Railway limits
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 30000
      pool-name: BookServiceRailwayHikariCP
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  
  main:
    lazy-initialization: true

server:
  port: ${SERVER_PORT:8080}

# External service URLs for Railway
book:
  service:
    url: ${BOOK_SERVICE_URL:http://localhost:8083}

# CORS configuration for Railway
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://qsngose.github.io,http://localhost:5500,http://127.0.0.1:5500,http://localhost:8080,http://localhost:3000}

# Logging configuration for Railway
logging:
  level:
    com.bookvault: INFO
    org.springframework: WARN
    org.hibernate: WARN
    org.springframework.data.redis: DEBUG
    io.lettuce: DEBUG
    org.springframework.boot.context.config: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Management endpoints for Railway
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true