server:
  port: 8082

spring:
  application:
    name: auth-service
  
  # Disable config server import check for local development
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  
  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/bookvault_auth
    username: bookvault
    password: bookvault123
    driver-class-name: org.postgresql.Driver
  
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# JWT configuration
jwt:
  secret: bookvault-secret-key-that-should-be-very-long-and-secure-in-production
  expiration: 86400000 # 24 hours in milliseconds

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

# Logging
logging:
  level:
    com.bookvault.auth: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

---
# Docker profile
spring:
  config:
    activate:
      on-profile: docker
  
  datasource:
    url: jdbc:postgresql://postgres:5432/bookvault_auth

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/ 