server:
  port: 8082

spring:
  application:
    name: auth-service
  
  # Database configuration for local development (Docker)
  datasource:
    url: jdbc:postgresql://localhost:5432/bookvault_auth
    username: bookvault
    password: bookvault123
    driver-class-name: org.postgresql.Driver
  
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # Redis configuration for local development (Docker)
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms

# Disable service discovery for local development
eureka:
  client:
    enabled: false

# JWT configuration
jwt:
  secret: bookvault-secret-key-that-should-be-very-long-and-secure-in-production
  expiration: 86400000 # 24 hours in milliseconds

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    com.bookvault.auth: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 