# Auth Service Configuration
server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookvault_auth
    username: bookvault
    password: bookvault123
    driver-class-name: org.postgresql.Driver

  redis:
    host: localhost
    port: 6379
    timeout: 2000ms

# JWT Configuration
jwt:
  secret: mySecretKey
  expiration: 86400000

# Docker profile override
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/bookvault_auth
  redis:
    host: redis 