[build]
builder = "NIXPACKS"
buildCommand = "cd shared && mvn clean install -DskipTests -B && cd .. && mvn clean package -DskipTests -B"

[deploy]
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
startCommand = "java -Xmx450m -jar target/*.jar"

[env]
SPRING_PROFILES_ACTIVE = "railway"
SERVER_PORT = "8080" 