[build]
builder = "NIXPACKS"
buildCommand = "mvn clean package -DskipTests -B"

[deploy]
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
startupTimeout = 600
startCommand = "java -Xmx450m -jar target/*.jar"

[env]
SPRING_PROFILES_ACTIVE = "railway"